#!/usr/bin/env python3
"""Generate the report-model JSON Schema and frontend TypeScript declarations."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from Core.report_model import ReportModel  # noqa: E402


SCHEMA_PATH = ROOT / "docs/schema/report-model-v1.schema.json"
TYPES_PATH = ROOT / "dashboard/src/generated/report-model.ts"


def _ts_type(schema: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    variants = schema.get("oneOf") or schema.get("anyOf")
    if variants:
        return " | ".join(_ts_type(item) for item in variants)
    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(_ts_type({"type": item}) for item in schema_type)
    if schema_type == "array":
        return f"Array<{_ts_type(schema.get('items', {}))}>"
    if schema_type == "object":
        properties = schema.get("properties", {})
        if properties:
            required = set(schema.get("required", []))
            fields = [
                f"{json.dumps(name)}{'?' if name not in required else ''}: {_ts_type(value)}"
                for name, value in properties.items()
            ]
            return "{ " + "; ".join(fields) + " }"
        if isinstance(schema.get("additionalProperties"), dict):
            value_schema = schema["additionalProperties"]
            return f"Record<string, {_ts_type(value_schema)}>"
        patterns = schema.get("patternProperties", {})
        if patterns:
            value_types = " | ".join(_ts_type(value) for value in patterns.values())
            return f"Record<string, {value_types}>"
        return "Record<string, unknown>"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "string":
        return "string"
    return "unknown"


def _typescript(schema: dict) -> str:
    lines = [
        "/* Generated by scripts/generate_report_schema.py. Do not edit. */",
        "",
    ]
    for name, definition in schema.get("$defs", {}).items():
        if definition.get("type") == "object" and "properties" in definition:
            lines.append(f"export interface {name} {_ts_type(definition)}")
        else:
            lines.append(f"export type {name} = {_ts_type(definition)};")
        lines.append("")
    lines.append(f"export type ReportModel = {_ts_type(schema)};")
    lines.append("")
    return "\n".join(lines)


def generated_content() -> tuple[str, str]:
    schema = ReportModel.model_json_schema(
        mode="serialization",
        ref_template="#/$defs/{model}",
    )
    schema["$id"] = "https://specterops.github.io/janus/schema/report-model-v1.schema.json"
    schema["title"] = "Janus Report Model v1"
    schema_text = json.dumps(schema, indent=2, sort_keys=True) + "\n"
    return schema_text, _typescript(schema)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero when checked-in generated files are stale",
    )
    args = parser.parse_args()
    expected = dict(zip((SCHEMA_PATH, TYPES_PATH), generated_content(), strict=True))

    if args.check:
        stale = [
            str(path.relative_to(ROOT))
            for path, content in expected.items()
            if not path.exists() or path.read_text(encoding="utf-8") != content
        ]
        if stale:
            print("Generated report-model artifacts are stale:")
            for path in stale:
                print(f"  - {path}")
            print("Run `make schema` and commit the results.")
            return 1
        print("Report-model schema and TypeScript declarations are current.")
        return 0

    for path, content in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"Wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
